version: '3.9'
services:
  sql_server:
    build: .
    container_name: sql_server
    command: ["python3", "sql_server.py"]
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
  vector_server:
    build: .
    container_name: vector_server
    command: ["python3", "vector_server.py"]
    ports:
      - "8002:8002"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
  client:
    build: .
    container_name: mcp_client
    command: ["uvicorn", "client:app", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    depends_on:
      - sql_server
      - vector_server
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
